name: Github Pages deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: '16.x'
        
    - name: Installing my packages
      run: npm install

    - name: Build my App
      run: npm run build && npm run start && touch ./out/.nojekyll
